---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu
    driver:
      image: ubuntu:latest
      platform: ubuntu
  - name: centos
    driver:
      image: centos:latest
      platform: centos

suites:
  - name: default
    run_list:
      - recipe[freeradius::default]
